export const RESPONSE = 'RESPONSE';
export const CLEAR_RESPONSE = 'CLEAR_RESPONSE';
export const SEARCH = 'SEARCH';
export const ADD_TO_SEARCHES = 'ADD_TO_SEARCHES';
export const DELETE_SEARCH_FROM_HISTORY = 'DELETE_SEARCH_FROM_HISTORY';
export const REDIRECT_TO_RESULTS_PAGE = 'REDIRECT_TO_RESULTS_PAGE';

export const FAVS = 'FAVS';
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const DELETE_FAV_FROM_FAVOURITES = 'DELETE_FAV_FROM_FAVOURITES';
export const CLEAR_FAVOURITES = 'CLEAR_FAVOURITES';

// STATE FIELDS
