export const RESPONSE = 'RESPONSE';
export const CLEAR_RESPONSE = 'CLEAR_RESPONSE';
export const SEARCH = 'SEARCH';
export const ADD_TO_SEARCHES = 'ADD_TO_SEARCHES';
export const DELETE_SEARCH_FROM_HISTORY = 'DELETE_SEARCH_FROM_HISTORY';
export const REDIRECT_TO_RESULTS_PAGE = 'REDIRECT_TO_RESULTS_PAGE';

// STATE FIELDS
